//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCDemo
{
    using System;
    using System.Collections.Generic;
    
    public partial class f_user_data
    {
        public int d_user_id { get; set; }
        public int d_login_id { get; set; }
        public System.DateTime f_last_login_dt { get; set; }
    
        public virtual d_login_data d_login_data { get; set; }
        public virtual d_users d_users { get; set; }
    }
}
